const router = require("express").Router()
const drugRouter = require("./drug.routes")
const patientRouter = require("./patient.routes")
const foodRouter = require("./food.routes")
const foodCategoryRouter = require("./foodcategory.routes")
const userRoutes = require("./user.routes")
const pageRouter = require("./pages.routes")
const authRoutes = require("./auth.routes")
const evaluationRoutes = require("./evaluation.routes")

router.use("/pacientes", patientRouter)
router.use("/farmacos", drugRouter)
router.use("/nutrientes", foodRouter)
router.use("/food-categories", foodCategoryRouter)
router.use("/users", userRoutes)
router.use("/evaluation", evaluationRoutes)
router.use("/pages", pageRouter)
router.use("/auth", authRoutes)

module.exports = router